### ISSUE TITLE
Manual has a mistake in wording.

### ISSUE THREAD

**Issue by ebraiman** [bigtreetech/SKR-Pico#1]
"Under CAUTION:
1. If you want to use a motor drive current of more than 0.8A, it is recommended to use a fan to actively heat the drive chip."

This should read, "1. If you want to use a motor drive current of more than 0.8A, it is recommended to use a fan to actively cool the drive chip."

**Comment by bigtreetech** [comment]
fixed in https://github.com/bigtreetech/SKR-Pico/commit/8b32e00e76b69a40d995f495c76d2c5cf97e7c53. Thank you very much!
